language: node_js

os:
- linux
- osx

node_js:
- '8'

install:
- npm install --build-from-source
- npm run tsc
- npm run tslint
- prebuild --all -u "$NODE_PRE_GYP_GITHUB_TOKEN" -t 1.6.10 -r electron

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install g++-4.8 ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8 ; fi

script:
- npm test
