language: node_js
os:
  - linux
  - osx
env:
  global:
  - secure: "qEdwCY/ilHkqWkqasN5MgWCnzzop4lEYkbpxEiVMTZBY12p4uV6ysPQ+ZLZcx10Cg90RIQlsPeEANIhCzkWfnQi+ySmeiKY9JR2eSnb69wM7dBQ/uxv04eVChAlZSsDHwmTIIzIzZFsrWrcwwJaENGCJYKqZ9LKOiGFGQ8Is09A="
  matrix:
  - TRAVIS_NODE_VERSION="7" ARCH="x64"
  - TRAVIS_NODE_VERSION="8" ARCH="x64"
  - TRAVIS_ELECTRON_VERSION="1.6.10" ARCH="x64" TRAVIS_NODE_VERSION="7"
  - TRAVIS_ELECTRON_VERSION="1.6.10" ARCH="x64" TRAVIS_NODE_VERSION="8"
node_js:
  - "7"
  - "8"
install:
  - npm install
  - npm run tsc
before_install:
  - PUBLISH_BINARY=true
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install g++-4.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8 ; fi
- >
  if [[ ! -z $TRAVIS_ELECTRON_VERSION ]]; then
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
    fi
    export npm_config_target=$TRAVIS_ELECTRON_VERSION
    export npm_config_arch=$ARCH
    export npm_config_disturl=https://atom.io/download/atom-shell
    export npm_config_runtime=electron
    npm install --arch=$ARCH electron@$TRAVIS_ELECTRON_VERSION
    npm install electron-mocha
    echo "installed Electron $TRAVIS_ELECTRON_VERSION"
  fi
  - npm install --build-from-source
script:
  - npm test
  - npm run tslint
  - node-pre-gyp package
  - node-pre-gyp-github publish --release
  - node-pre-gyp clean
