version: "{build}"
build: off
skip_tags: true

environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "8"
    - electron_version: "1.6.10"
      nodejs_version: "7"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.2;%path%
  - npm install
  - npm run install
  - npm run tsc
  - npm run tslint
  - for /f %%i in ('node -v') do set exact_nodejs_version=%%i
  - prebuild -b %exact_nodejs_version% --strip

on_success:
  - for %%i in (prebuilds\*) do appveyor PushArtifact %%i
